#!/bin/sh
# ==============================================================================
# $RCSfile: makereg,v $
# 
#    DESC : TH Regular Clean,Build,Run on gcc with Consolidated Log
# 
#  AUTHOR : Rick Foos, ECL, LLC 
# 
#     CVS : $Revision: 1.7 $
# ------------------------------------------------------------------------------
#  Copyright (c) 1998-2002 by the EDN Embedded Microprocessor 
#  Benchmark Consortium (EEMBC), Inc. All Rights Reserved.
# ==============================================================================
# For each TOOLCHAIN
make VER=$VER TOOLCHAIN=gcc LITE= $1
if [ ! -e ../gcc_time${VER}.log ]; then
cat ../util/awk/titletime.txt >../gcc_time${VER}.log
fi
if [ -e gcc_time${VER}.log ]; then
cat gcc_time${VER}.log >>../gcc_time${VER}.log
fi

